### ISSUE TITLE
Unable to join the Slack community

### ISSUE THREAD

**Issue by aeturrell** [uk-tre/website#10]
Hello

Very interested in joining and learning more about deploying TREs, especially in the public sector, but I'm unable to join the slack channel because I don't have a .ac.uk email address (and I expect my public sector email will block anything from slack as it is banned).

Am I able to join?

Many thanks

**Comment by manics** [comment]
Our Slack channel is part of the UK Research Software Engineers Slack. .ac.uk email addresses are automatically approved, but you should be able to join with any email address, though one of the moderators will need to approve it.

We're aware the current Slack doesn't work for everyone, but unfortunately we've not found a single chat solution that does, every organisation has different rules on what it allows and blocks!

Probably the best option is to join the mailing list if you haven't already:
https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?SUBED1=RSE-TRE-COMM&A=1

**Comment by manics** [comment]
Our Slack channel is part of the UK Research Software Engineers Slack. .ac.uk email addresses are automatically approved, but you should be able to join with any email address, though one of the moderators will need to approve it.

We're aware the current Slack doesn't work for everyone, but unfortunately we've not found a single chat solution that does, every organisation has different rules on what it allows and blocks!

Probably the best option is to join the mailing list if you haven't already:
https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?SUBED1=RSE-TRE-COMM&A=1

**Comment by aeturrell** [comment]
Slack is great! I just couldn't seem to join without an .ac.uk email. I have indeed joined the email list. Thanks for your help.
