### ISSUE TITLE
Restructure based on deliverables

### ISSUE THREAD

**Issue by harisood** [uk-tre/website#20]
### Detail

To sync up the repos and project board with the website, we are converting the DARE funding proposal into an easier to read MarkDown file with labeled deliverables. This links into a slight restructuring of the website to make it more accessible to others.

Atm we don't have a new design, but want to start adding content - once we have the content we want we can start to how a website will shape up!

### Actions

- [x] Start the restructure
- [x] Add the deliverables one pager as referenced here: https://github.com/uk-tre/community-management/issues/21

**Comment by harisood** [comment]
This is being covered in #21, needs review

**Comment by Davsarper** [comment]
Where do we stand with the [associated PR](https://github.com/uk-tre/website/pull/21), it is approved but I am unsure wheter or not we addressed redirects.
Also slightly confused what the difference is between this issue and https://github.com/uk-tre/community-management/issues/21
https://github.com/orgs/uk-tre/projects/1?pane=issue&itemId=44289577 depends on finalising this one as well to create the right categories for the board view

**Comment by Davsarper** [comment]
This has been on hold waiting for the new website, the associated PR is likely to be closed and a new one wiht updated content created

**Comment by harisood** [comment]
Not relevant anymore, see issue 16 in website repo for latest details
